### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by svengato** [legumeinfo/taxon-symbology#44]
- [x] Create a branch for the release.
- [x] Update the dependencies. The dependabot PR backlog is not comprehensive and doesn't include transitive dependencies, and merging them one at a time tends to break things, so the best way to do this is manually with `npm`.
- [x] Do a test build of the NPM package on your local machine so you know if something is going off the rails before the automated build action on GitHub.
- [x] Bump the `"version"` number in `package.json` and reinstall the dependencies so the correct version number is in `package-lock.json`.
- [x] Open a PR that merges the release branch into main.
- [x] Merge the release PR after it passes testing and review.
- [x] Tag a corresponding release on GitHub. This will trigger an automated NPM package build on GitHub. If the package build succeeds it will be automatically published to NPM.

**Comment by svengato** [comment]
One step to go: Tag a corresponding release on GitHub.
Do I need to explicitly add the **What's Changed** and **New Contributors** sections, or does it automatically generate those based on the commit messages?

For What's Changed, I have:
- Added unit tests. (you did this after v1.0.0)
- Added more legume species.
- Revised taxon colors for greater similarity between related taxa.
- Updated package dependencies.

**Comment by svengato** [comment]
It looks like I do need to add these.

**Comment by alancleary** [comment]
> One step to go: Tag a corresponding release on GitHub. Do I need to explicitly add the **What's Changed** and **New Contributors** sections, or does it automatically generate those based on the commit messages?

Just click the "Generate release notes button"

**Comment by svengato** [comment]
**Generate release notes** is disabled, I will experiment with that.

**Comment by alancleary** [comment]
> **Generate release notes** is disabled, I will experiment with that.

If you hover your mouse over the disabled button a tooltip tells you to create a valid tag first, which you can do via the "Choose a tag" dropdown to the left of the button...

**Comment by svengato** [comment]
It works now, I think I entered the tag but did not hit the Enter or Tab key.

**Comment by svengato** [comment]
Okay, here goes (Publish release) ...
It appears correct, it added the source code as well. Thanks for your help!
